FROM eclipse-temurin:21-jre
ENV MB_PLUGINS_DIR=/plugins
ENV JAVA_OPTS="-Dduckdb.read_only=false"
RUN mkdir -p ${MB_PLUGINS_DIR} /app
ADD https://downloads.metabase.com/v0.59.4/metabase.jar /app/metabase.jar
ADD https://github.com/motherduckdb/metabase_duckdb_driver/releases/download/1.5.1.0/duckdb.metabase-driver.jar ${MB_PLUGINS_DIR}/
EXPOSE 3000
CMD ["java", "-Dduckdb.extensions=ducklake,postgres", "-jar", "/app/metabase.jar"]